<?php
/**
 * @file
 * Google Translate for Drupal
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function g_translate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.g_translate':
      $output = '<h3>' . t('GTranslate Resources') . '</h3>';
      $output .= '<ul class="links">';
      $output .= '<li><a href="https://gtranslate.io/docs" target="_blank">GTranslate Documentation</a></li>';
      $output .= '<li><a href="https://gtranslate.io/videos" target="_blank">GTranslate Videos</a></li>';
      $output .= '<li><a href="https://gtranslate.io/#faq" target="_blank">GTranslate FAQ</a></li>';
      $output .= '</ul>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function g_translate_permission() {
  return array(
    'g_translate settings' => array(
      'title' => t('Manage GTranslate settings'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function g_translate_theme($existing, $type, $theme, $path) {
  return array(
    'gtranslate' => array(
      'variables' => array('gtranslate_html' => NULL),
    ),
  );
}
